apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-app
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.source.repoURL }}
    targetRevision: {{ $.Values.source.targetRevision }}
    path: {{ $.Values.global.clusterConfigPath }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: {{ $.Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ $.Values.syncPolicy.automated.selfHeal }}